# Generated by Django 5.2.13 on 2026-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("like", "Like"),
                    ("dislike", "Dislike"),
                    ("heart", "Heart"),
                    ("fire", "Fire"),
                ],
                max_length=20,
            ),
        ),
    ]
